import { Rubik } from 'next/font/google'

const rubik = Rubik({
  subsets: ['latin'],
  weight: '300',
});

export const metadata = {
  title: 'Auden App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={rubik.className}>{children}</body>
      </html>
    </>
  )
}
